export const ErrorMessage = Object.freeze({
    TOKEN_EXPIRED           : "JWT EXPIRED",
    INVALID_JWT_TOKEN       : "JWT IS INVALID",
    INVALID_SIGNATURE       : "INVALID JWT SIGNATURE",
    INTERNAL_SERVER_ERROR   : "SOME ERROR OCCURRED",
    SOMETHING_WENT_WRONG    : "SOMETHING WENT WRONG",
    MOB_ALREADY_EXIST       : "MOBILE NUMBER IS ALREADY EXIST",
    USER_NOT_FOUND          : "USER NOT FOUND",
    NO_AUTH_TOKEN           : "AUTH TOKEN NOT FOUND",
    USER_NOT_AUTHORIZED     : "USER IS NOT AUTHORIZED TO ACCESS THIS API",
    CLOUDINARY_IMG_URL      : "CLOUDINARY IS NOT GENERATED THE IMAGE URL",
    DATA_NOT_UPDATED        : "NO DATA HAS BEEN UPDATED",
    BAD_REQUEST_ORIGIN      : "ORIGIN MISSING",
    PASSWORD_WRONG          : "WRONG PASSWORD"
});

export const SuccessMessage = Object.freeze({
    SIGN_UP      : "USER IS SIGNUP SUCCESSFULLY",
    DATA_FETCHED : "DATA FETCHED SUCCESSFULLY",
    DATA_UPDATED : "DATA IS UPDATED SUCCESSFULLY",
    MENU_CREATED : "SCARP MENU IS CREATED SUCCESSFULLY",
    DATA_DELETED : "DATA HAS BEEN DELETED"
});
